### ISSUE TITLE
Box template fallback

### ISSUE THREAD

**Issue by HonzaMikula** [ella/ella#126]
There is currently fallback for box templates like this: box/category/<tree_path>/content_type/<app>.<model>/<slug>/<box_name>.html.

I have a problem with category. In many times I need distinguish template for box on base of category from which is the template call. In current fallback system I have to do like this:

page/category.html

{% for article in listings %}
    {% box listing for article %}{% endbox %}
{% endfor %}

page/category/homepage/category.html

{% for article in listings %}
    {% box listing_hp for article %}{% endbox %}
{% endfor %}

Because category in fallback system is defined by object main category. Not by category from which you call the box template.

So I would prefer distinguish template on level of boxes. Something like this:

general box for article: box/content_type/articles.article/listing.html 

and

specific box for homepage or another categories: box/category/homepage/content_type/articles.article/listing.html

But that's not possible now.

I know that often it's useful to distinguish box templates on base of object main category, but very often it would be useful to distinguish on base of category from  which box template is called.

**Comment by honzakral** [comment]
This is not what boxes are for, use standard django methods to do what you want: different templates, template inheritance, conditionals, includes, variables.

Alternatively pass in the category it's being displayed from to the params of the box so you can access this inside:

{% box xx for obj %}
  displayed_in: {{ category.tree_path }}
{% endbox %}

then you can do
{{ box.params.displayed_in }}
inside the box template.

Closing since this is not in scope of ella to fix imho, it would be both too complex to understand and inconsistent with how other templates work.

Also it would break caching somewhat.

For you I'd suggest creating a different template tag that would behave as you wish, if you come up with a good name and undestandable docs, submit a pull request, it would be a nice addition :)

Thanks!
