### ISSUE TITLE
Competition/Quizes answers not added on save

### ISSUE THREAD

**Issue by xaralis** [ella/ella#29]
When saving competition/quiz, created answers along with responses are not saved (not even one of them).

Prefered solution is major simplification/refactoring of JS widgets that are used since current ones are highly confusing to the users.

**Comment by xaralis** [comment]
Please have a look why the save action is failing a propose some solution. Thanks.

**Comment by Sixtease** [comment]
The problem seems to be in a superfluous malformed field in a data structure coming from the backend.

In /polls/contest/add/, there are two empty answers present after load. Both contain a hidden input whose name equals "choices_widget". The value of the first is "`question_set-0-choices`", while the value of the second is "`question_set-__prefix__-choices`". The JavaScript code expect there to be a number, so the latter value causes an error. Apparently, the `__prefix__` part is an unexpanded placeholder.

The easiest solution would be to remove the second field from the data structure.

It's generated in the template
ella/newman/templates/newman/edit_inline/poll_question.html
in a loop commented {# answer options #}.
