### ISSUE TITLE
Switch django-tagging to django-taggit

### ISSUE THREAD

**Issue by xaralis** [ella/ella#33]
I am proposing exchange of tagging application for ella 2.0. There are several important reasons to do this.
### django-tagging is not maintained anymore

Last commits were introduced in the begging 2010 which most likely means it's not maintained anymore.

One one hand, it's _partially true_ for django-taggit as well. The last commit goes to spring of 2011. However, there is a big amount of living forks which looks like it will not die out any soon.

The bad news is that it looks like it's still not working properly in django 1.3 so some small praticipation might be needed.
### Current implementation makes it hard or almost impossible to sort tag list by date

Sorting tagged items by date is quite a must-have feature and without it, it just makes tags a little unusable overally. The main reason for this is following piece of code:

``` python
def get_tagged_publishables(tag):
    now = datetime.now()
    queryset = Publishable.objects.filter(
        Q(placement__publish_to__isnull=True) | Q(placement__publish_to__gt=now),
        placement__publish_from__lt=now).distinct()
    return TaggedItem.objects.get_by_model(queryset, tag)
```

This effectively prevents us from sorting by anything in DB. Only solution would be to sort in Python (not a good one though).
### django-tagging allows for bad characters in URL

One can enter something with "/" character in it which then breaks in tag listing. Ella might be solving this, but that's not a good way to go.
### There is known way to migrate from tagging to taggit that could be automated in migrations

Simply adhere to following blog post, only automate it a little: http://birdhouse.org/blog/2011/04/17/migrate-django-tagging-taggit/.

**Comment by honzakral** [comment]
I would like to remove the tagging apps altogether from ella and maybe then add an ella-taggit app as external project.

**Comment by xaralis** [comment]
Oh yeah, that sounds even better ;)

**Comment by HonzaMikula** [comment]
I don't know exactly what this change of application mean. But here is mine point of view what possibilities tags should have or nice to have.

This is list of things editor should have option to fill or change:
- title
- slug
- description
- content

In publishable object there should be a option prioritize assigned tags, because editor should have a option to say which of tags is the main. There could be consequences to related object and so on. 

Also editor should have a option to assign hidden tags for categorizing object in admin not in frontend. 

I have also experience that editor would like to make hierarchy from tags. For example: Cars (Skoda, BMW, VW, Audi,..), Animals (cat, dog,..). It's way how editor can automatically get better related object by only using right tags.

So what do you think?

**Comment by honzakral** [comment]
@HonzaMikula you are overengineering this by a wide margin. Trust me, I have done the same. Editors always want more control that they are never going to use, I say ella should go with the minimal approach and of anybody wants more, just let them extend the plug-in and add their own stuff.

I am closing this since this discussion should move to the new ella-tagging repo.

**Comment by xaralis** [comment]
See new ella-taggit repo: https://github.com/ella/ella-taggit. It's a bridge to django-taggit with features superior to django-tagging (and ella-tagging respectively).
