### ISSUE TITLE
Final testing before accepting 2.1.0

### ISSUE THREAD

**Issue by xaralis** [ella/ella#40]
Looks like we have fixed all the issues that were blocking final django-1.3 compatibility release. We have put the changes into **proposals/2.1.0** branch (last changes in commit 0b5f605a46). Please, have a look at this version and report any new errors.

Just to let you know, this has been put into proposals so we are **not accepting any new features**, only bug fixes related to Django 1.3 compatibility.

**Comment by kvbik** [comment]
sweet, looking forward ;)

**Comment by whit** [comment]
There is not differences between proposal and master?

**Comment by xaralis** [comment]
That's right because proposal branch has just been made from current state of master branch.

From now on, proposals is freezed for new changes and all commits related to django 1.3 will be made to proposals branch from which they will be merged back to master. Is it clear?

**Comment by honzakral** [comment]
Hey, thanks for all the work.

I would have a simple wish for 2.1.0: remove all one-time apps that aren't going to be used:
- catlocks
- contact_form
- db_templates
- discussions
- ellaexports ??
- ellatagging (as discussed in #33)
- oldcomments
- ratings
- sendmail

I am not saying they don't wok (even though in some cases it's true) but they are not up to standard and have generally no place in a generic CMS because their functionality is very limited. For some of those, external apps exist that could replace them, others are boken and others can be made into a fully external module.

Can we do this in time for 2.1.0 ? I will be happy to do the removal myself, just want to make sure evryone is more or less OK with the idea.

**Comment by whit** [comment]
@xaralis yep!

@HonzaKral If i remember, this cleanup was planned for 3.x branch. No problem to do it earlier for us, but just except ellatagging app. Or to have new external tagging app that can migrate data from old one.

**Comment by honzakral** [comment]
@whit oh, sorry, didn't remember about the plans. ignore me then and wake me up when it's time for 3.x and I will be happy to do it.

**Comment by whit** [comment]
@HonzaKral It's time just now! If you can do this work, create new branch "3.x" or "future/3.x" and hurry to cleanup :)

**Comment by kvbik** [comment]
be careful with encouraging @HonzaKral in deleting stuff. he enjoys that **very** much ;).

**Comment by xaralis** [comment]
Looks like no complaints whatsoever. Are we ready for release then?

**Comment by whit** [comment]
2.1.x released, as 2.x line stable branch you can still use `proposal/2.1`.
