### ISSUE TITLE
Uncaught exception in QuizWizard located in ella/polls/views.py

### ISSUE THREAD

**Issue by jezradek** [ella/ella#74]
There is no problem with adding new quiz(test) via newman.
But opening url of the quiz raises this exception. The exception is IndexError: list index out of range.

**Comment by xaralis** [comment]
Is everything created properly prior to opening quiz page?

Please attach full traceback.

**Comment by jezradek** [comment]
Yeah, quiz wasn't created properly, there wasn't added any question. However I am not sure if this is proper behaviour ...  Maybe newman should inform you that you didn't fill the question or something ...

I think that this part of traceback is enough for you :) ... ( especially 'question' : quiz.questions[0], ... ) ...
/home/radek/.virtualenvs/dum_a_zahrada/src/ella/ella/polls/views.py in **init**
class QuizWizard(FormWizard):
    def **init**(self, quiz):
        form_list = [ QuestionForm(q) for q in quiz.questions ]
        print 'form_list: ', len(form_list)
        super(QuizWizard, self).**init**(form_list)
        self.quiz = quiz
        self.extra_context = {'object' : quiz,
                               'question' : quiz.questions[0], ...
                                'category' : quiz.category,}
        # ?? ?? ?? ??
        #super(QuizWizard, self).**init**(form_list)
        # ?? ?? ?? ??
    def get_template(self, step):

Lastly csrf protection, which was mentioned here at other topic, is missing there, should I report it as a new issue?

**Comment by xaralis** [comment]
Well, this is mostly an polls issue after all which should act more error-prone and definitely not raise an exception when there is no question available.

Please, post this issue to **ella-polls** project instead of this one as no refactoring related to plugins will probably occur here anymore. This also relates to newman which cannot be responsible for quiz page not being validated properly. All validation should occur in models and `admin.py` / `newman_admin.py` where not possible .

And please, have a look at markdown syntax supported thorough GitHub (blue link saying "GitHub Flavored Markdown") and try to make the traceback more human-readable posting it as code block or something.

**Comment by xaralis** [comment]
Closing this, as it's not related to Ella anymore.

**Comment by jezradek** [comment]
Okey ;)
